[Appearance]
color_scheme_path=
custom_palette=false
icon_theme=Papirus-Dark
standard_dialogs=default
style=kvantum

[Fonts]
fixed="Share Tech Mono,10,-1,5,50,0,0,0,0,0"
general="Exo 2,10,-1,5,50,0,0,0,0,0"
