# hyprpaper.conf — RaBbLE-OS wallpaper configuration
# Wallpaper assets live in config/wallpapers/ → deployed to ~/.config/wallpapers/

preload  = ~/.config/wallpapers/RaBbLE_WP.PNG

wallpaper {
    monitor = eDP-1
    path = ~/.config/wallpapers/RaBbLE_WP.PNG
    fit_mode = contain
}

wallpaper {
    monitor = HDMI-A-1
    path = ~/.config/wallpapers/RaBbLE_WP.PNG
    fit_mode = contain
}

splash = false
