# Catppuccin Mocha Mauve — Qt6ct color scheme
# License: MIT (https://github.com/catppuccin/kde)
# Palette: https://catppuccin.com/palette (Mocha, Mauve accent)
# Roles (21 values, QPalette order):
#   WindowText, Button, Light, Midlight, Dark, Mid, Text, BrightText, ButtonText,
#   Base, Window, Shadow, Highlight, HighlightedText, Link, LinkVisited,
#   AlternateBase, NoRole, ToolTipBase, ToolTipText, PlaceholderText
[ColorScheme]
active_colors=#ffcdd6f4, #ff313244, #ff585b70, #ff45475a, #ff11111b, #ff313244, #ffcdd6f4, #ffcdd6f4, #ffcdd6f4, #ff1e1e2e, #ff1e1e2e, #ff11111b, #ffcba6f7, #ff1e1e2e, #ff89b4fa, #ffcba6f7, #ff181825, #00000000, #ff181825, #ffcdd6f4, #ff6c7086
disabled_colors=#ff6c7086, #ff313244, #ff585b70, #ff45475a, #ff11111b, #ff313244, #ff6c7086, #ff6c7086, #ff6c7086, #ff1e1e2e, #ff1e1e2e, #ff11111b, #ff45475a, #ff6c7086, #ff89b4fa, #ff6c7086, #ff181825, #00000000, #ff181825, #ff6c7086, #ff45475a
inactive_colors=#ffbac2de, #ff313244, #ff585b70, #ff45475a, #ff11111b, #ff313244, #ffbac2de, #ffbac2de, #ffbac2de, #ff1e1e2e, #ff1e1e2e, #ff11111b, #ff585b70, #ffbac2de, #ff89b4fa, #ff6c7086, #ff181825, #00000000, #ff181825, #ffbac2de, #ff6c7086
