-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- dotfiles/hyprland/conf.d/autostart.conf

-- =============================================================================

-- exec-once: runs once on Hyprland start

-- exec:      runs on every reload

-- =============================================================================

-- ── System services ───────────────────────────────────────────────────────────





-- ── GTK4 / libadwaita dark mode ───────────────────────────────────────────────

-- libadwaita reads color-scheme from org.gnome.desktop.interface regardless of DE.

-- Must fire after dbus-update-activation-environment so dconf daemon is reachable.


-- ── Notification daemon ───────────────────────────────────────────────────────


-- ── Clipboard ─────────────────────────────────────────────────────────────────



-- ── Idle & lock ───────────────────────────────────────────────────────────────

-- hypridle requires ~/.config/hypr/hypridle.conf to exist or it aborts (sig 6)


-- Lid close suspend is handled by logind (99-rabble-lid.conf: HandleLidSwitch=suspend).

-- hypridle's before_sleep_cmd = loginctl lock-session fires hyprlock before suspend.

-- ── Wallpaper ─────────────────────────────────────────────────────────────────


-- Config: ~/.config/hypr/hyprpaper.conf — deployed by Ansible, wallpaper at ~/.config/hypr/wallpapers/

-- ── Shell UI ──────────────────────────────────────────────────────────────────


-- exec-once = quickshell   # Phase 1.2 — replace waybar once QML bar is stable

-- ── Network manager tray ──────────────────────────────────────────────────────


-- OSD server for volume/brightness/caps lock feedback


-- ── HDMI hotplug ──────────────────────────────────────────────────────────────


-- ── Split direction daemon ────────────────────────────────────────────────────

-- Enforces persistent split mode (Super+T toggle). Re-applies preselect after

-- every new window so the mode holds until toggled again.


-- ── sCoRE Usage Tracker daemons ───────────────────────────────────────────────

-- Two persistent background processes feed the Waybar Claude/Codex pills:

--

--   score-usage-api-poll.py    pulls Anthropic's official 5h/7d usage % from

--                              claude.ai's internal API (via the Firefox session

--                              cookie you already hold) every ~90s, and writes

--                              ~/.cache/rabble/llm-usage-latest.json

--

--   score-status-daemon.sh     re-parses ~/.claude + ~/.codex transcripts and

--                              rebuilds each pill's full text/tooltip every few

--                              seconds, caching to ~/.cache/rabble/score-<mode>.json

--                              with the busy glyph left as a literal "@GLYPH@"

--                              placeholder — Waybar's score-glyph-stream.sh

--                              repaints just that glyph at high frequency on

--                              top of the cache, so the animation stays smooth

--                              without re-running the expensive parse every tick

--

-- See each script's header comment for the full two-tier rationale.



-- Autostart
hl.on("hyprland.start", function()
    hl.exec_cmd("systemctl --user start hyprpolkitagent")
    hl.exec_cmd("dbus-update-activation-environment --systemd --all")
    hl.exec_cmd("systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd("systemctl --user start xdg-desktop-portal-hyprland")
    hl.exec_cmd("gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'")
    hl.exec_cmd("mako")
    hl.exec_cmd("wl-paste --type text --watch cliphist store")
    hl.exec_cmd("wl-paste --type image --watch cliphist store")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("hyprpaper")
    hl.exec_cmd("waybar")
    hl.exec_cmd("nm-applet --indicator")
    hl.exec_cmd("swayosd-server")
    hl.exec_cmd("~/.config/hypr/scripts/hdmi-hotplug.sh")
    hl.exec_cmd("~/.config/hypr/scripts/split-dir-daemon.sh")
    hl.exec_cmd("uv run ~/.config/waybar/scripts/score-usage-api-poll.py")
    hl.exec_cmd("~/.config/waybar/scripts/score-status-daemon.sh")
end)
