-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- dotfiles/hyprland/conf.d/env.conf

-- Runtime environment variables for Hyprland session.

-- Scale / DPI overrides are in machine.conf (ansible-generated).

-- ── Wayland ───────────────────────────────────────────────────────────────────

hl.env("XDG_SESSION_TYPE", "wayland")

hl.env("XDG_CURRENT_DESKTOP", "Hyprland")

hl.env("XDG_SESSION_DESKTOP", "Hyprland")

-- ── Qt ────────────────────────────────────────────────────────────────────────

hl.env("QT_QPA_PLATFORM", "wayland;xcb")

hl.env("QT_QPA_PLATFORMTHEME", "qt6ct")

hl.env("QT_STYLE_OVERRIDE", "kvantum")

hl.env("QT_WAYLAND_DISABLE_WINDOWDECORATION", 1)

hl.env("QT_AUTO_SCREEN_SCALE_FACTOR", 1)

-- ── GTK ───────────────────────────────────────────────────────────────────────

hl.env("GDK_BACKEND", "wayland,x11,*")

hl.env("GTK_THEME", "RaBbLE-Aether")

hl.env("GTK_USE_PORTAL", 1)

-- ── Apps ──────────────────────────────────────────────────────────────────────

hl.env("MOZ_ENABLE_WAYLAND", 1)

hl.env("ELECTRON_OZONE_PLATFORM_HINT", "auto")

hl.env("_JAVA_AWT_WM_NONREPARENTING", 1)

hl.env("SDL_VIDEODRIVER", "wayland")

-- ── Cursor ────────────────────────────────────────────────────────────────────

hl.env("HYPRCURSOR_THEME", "Bibata-Modern-Classic")

-- XCURSOR_SIZE and HYPRCURSOR_SIZE are set in machine.conf per display

-- ── NVIDIA hybrid (AMD primary, NVIDIA drives HDMI) ──────────────────────────

-- AQ_DRM_DEVICES: AMD first (primary renderer), NVIDIA second (HDMI scanout).

-- Colon-delimited, so pinned via the stable vendor-ID udev aliases (deployed by

-- ansible/roles/hardware/x64/asus_proart_p16/tasks/nvidia.yml Step 1c), NOT raw

-- card numbers — those renumber if Phase 2 (simpledrm suppression) lands.

hl.env("AQ_DRM_DEVICES", "/dev/dri/rabble-amdgpu-card:/dev/dri/rabble-nvidia-card")

hl.env("LIBVA_DRIVER_NAME", "nvidia")

hl.env("NVD_BACKEND", "direct")

-- Hardware cursors on NVIDIA Wayland cause artifacts — disable

hl.env("HYPRLAND_NO_HARDWARE_CURSORS", 1)

-- ── Editors / tools ───────────────────────────────────────────────────────────

hl.env("EDITOR", "nvim")

hl.env("VISUAL", "nvim")

hl.env("TERMINAL", "kitty")

hl.env("BROWSER", "firefox")
