-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- dotfiles/hyprland/conf.d/env.conf

-- Runtime environment variables for Hyprland session.

-- Scale / DPI overrides are in machine.conf (ansible-generated).

-- ── Wayland ───────────────────────────────────────────────────────────────────

hl.env("XDG_SESSION_TYPE", "wayland")

hl.env("XDG_CURRENT_DESKTOP", "Hyprland")

hl.env("XDG_SESSION_DESKTOP", "Hyprland")

-- ── Qt ────────────────────────────────────────────────────────────────────────

hl.env("QT_QPA_PLATFORM", "wayland;xcb")

hl.env("QT_QPA_PLATFORMTHEME", "qt6ct")

hl.env("QT_STYLE_OVERRIDE", "kvantum")

hl.env("QT_WAYLAND_DISABLE_WINDOWDECORATION", 1)

hl.env("QT_AUTO_SCREEN_SCALE_FACTOR", 1)

-- ── GTK ───────────────────────────────────────────────────────────────────────

hl.env("GDK_BACKEND", "wayland,x11,*")

hl.env("GTK_THEME", "RaBbLE-Aether")

hl.env("GTK_USE_PORTAL", 1)

-- ── Apps ──────────────────────────────────────────────────────────────────────

hl.env("MOZ_ENABLE_WAYLAND", 1)

hl.env("ELECTRON_OZONE_PLATFORM_HINT", "auto")

hl.env("_JAVA_AWT_WM_NONREPARENTING", 1)

hl.env("SDL_VIDEODRIVER", "wayland")

-- ── Cursor ────────────────────────────────────────────────────────────────────

hl.env("HYPRCURSOR_THEME", "Bibata-Modern-Classic")

-- XCURSOR_SIZE and HYPRCURSOR_SIZE are set in machine.conf per display

-- ── Machine-specific env (optional) ─────────────────────────────────────────

-- GPU pinning (AQ_DRM_DEVICES) and NVIDIA env are hardware-specific: the old
-- unconditional ProArt pin made Hyprland abort with "CBackend::create()
-- failed!" on every other machine (seen on the S236 test VM). Hardware
-- roles write conf_d/machine.lua; dotctl never deploys it, so on a machine
-- without one this is a no-op and aquamarine picks the GPU itself.

pcall(require, "conf_d.machine")

-- ── Editors / tools ───────────────────────────────────────────────────────────

hl.env("EDITOR", "nvim")

hl.env("VISUAL", "nvim")

hl.env("TERMINAL", "kitty")

hl.env("BROWSER", "firefox")
