-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- config/hyprland/conf.d/function_keys.conf

-- =============================================================================

-- Function Key Bindings — ASUS ProArt P16

--

-- OSD feedback provided by swayosd (must be running — see autostart.conf)

-- swayosd-server must be started before these binds will show overlays

--

-- Keys marked [REQUIRES ASUSCTL] will silently no-op until the hardware

-- role is fixed and asusd is running. The binds are correct — just dormant.

--

-- Key name reference:

--   XF86AudioMute, XF86AudioLowerVolume, XF86AudioRaiseVolume

--   XF86AudioMicMute

--   XF86MonBrightnessUp, XF86MonBrightnessDown

--   XF86KbdBrightnessUp, XF86KbdBrightnessDown, XF86KbdLightOnOff

--   XF86Display

--   XF86Launch1 (custom ASUS key — may vary by BIOS)

--   XF86Launch4 (Copilot/assistant key on ASUS — may vary)

--   XF86WebCam

-- =============================================================================

-- ── Volume ────────────────────────────────────────────────────────────────────

-- Mute / unmute audio output

hl.bind("XF86AudioMute", hl.dsp.exec_cmd("swayosd-client --output-volume mute-toggle"))

-- Volume down — hold to repeat

hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("swayosd-client --output-volume lower"), { repeating = true })

-- Volume up — hold to repeat

hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("swayosd-client --output-volume raise"), { repeating = true })

-- ── Microphone ────────────────────────────────────────────────────────────────

-- Mute / unmute microphone input

-- swayosd --input-volume mute-toggle shows OSD but doesn't reach PipeWire; wpctl does the real work

hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("sh -c \"wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle; swayosd-client --input-volume mute-toggle\""))

-- ── Brightness ────────────────────────────────────────────────────────────────

-- Brightness up — hold to repeat

-- --device amdgpu_bl1 pins swayosd to the display backlight, preventing it from

-- reading asus::kbd_backlight as the OSD source on ProArt P16.

hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("swayosd-client --brightness raise --device amdgpu_bl1"), { repeating = true })

-- Brightness down — hold to repeat

hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("swayosd-client --brightness lower --device amdgpu_bl1"), { repeating = true })

-- ── Keyboard Backlight ────────────────────────────────────────────────────────

-- [REQUIRES ASUSCTL] — asusd must be running for these to take effect

-- Once hardware role is fixed, these will work without changes here

-- Toggle keyboard backlight on/off (with keyboard icon OSD)

hl.bind("XF86KbdLightOnOff", hl.dsp.exec_cmd("~/.config/hypr/scripts/kb-brightness.sh toggle"))

-- Keyboard backlight up (with keyboard icon OSD)

hl.bind("XF86KbdBrightnessUp", hl.dsp.exec_cmd("~/.config/hypr/scripts/kb-brightness.sh up"))

-- Keyboard backlight down (with keyboard icon OSD)

hl.bind("XF86KbdBrightnessDown", hl.dsp.exec_cmd("~/.config/hypr/scripts/kb-brightness.sh down"))

-- ── Display ───────────────────────────────────────────────────────────────────

-- Display mode switcher — cycle monitor layouts via kanshi

-- kanshictl switch cycles through profiles defined in ~/.config/kanshi/config

hl.bind("XF86Display", hl.dsp.exec_cmd("kanshictl switch"))

-- ── Screen Capture ────────────────────────────────────────────────────────────

-- Captures pipe straight into swappy for annotate/save/discard.

-- Ctrl+S save (→ ~/Screenshots, see config/swappy/config) · Ctrl+C copy · Escape discard.

-- Full screen capture → swappy

hl.bind("Print", hl.dsp.exec_cmd("~/.config/hypr/scripts/screenshot.sh screen"))

-- Region select capture → swappy

hl.bind("SHIFT" .. " + " .. "Print", hl.dsp.exec_cmd("~/.config/hypr/scripts/screenshot.sh region"))

-- Region select capture → copy to clipboard (no file saved)

hl.bind("CTRL" .. " + " .. "Print", hl.dsp.exec_cmd("grim -g \"$(slurp)\"-| wl-copy"))

-- ── Emoji Launcher ────────────────────────────────────────────────────────────

-- Requires: rofimoji (dnf install rofimoji)

-- rofimoji uses fuzzel as the picker backend

-- On ASUS, the emoji key may appear as XF86Messenger or have no keysym — SUPER+Period as fallback

hl.bind("XF86EmojiPicker", hl.dsp.exec_cmd("rofimoji --selector fuzzel"))

-- ── ASUS Custom Keys ──────────────────────────────────────────────────────────

-- [REQUIRES ASUSCTL for full platform integration]

-- XF86Launch1 = ROG/ASUS custom key (physical Armoury Crate button on some models)

-- XF86Launch4 = Copilot / AI assistant key (present on newer ASUS models)

-- Exact keysyms depend on BIOS version — verify with: wev | grep -i launch

-- Custom ASUS key — launch a terminal scratchpad or system monitor

hl.bind("XF86Launch1", hl.dsp.exec_cmd("kitty --title \"rabble-scratch\""))

-- Assistant key — placeholder until RaBbLE entity is wired in Phase 2/3

-- For now launches a Claude Code session or aichat

hl.bind("XF86Assistant", hl.dsp.exec_cmd("kitty --title \"rabble-assistant\" -e bash -c \"echo 'RaBbLE entity dormant // %ENTITY_DORMANT%'; bash\""))

-- ── Caps Lock ─────────────────────────────────────────────────────────────────

-- Hyprland handles Caps Lock natively — the LED state is managed by the compositor

-- swayosd shows a caps lock OSD indicator when the key is pressed

-- No explicit bind needed — just ensure swayosd-server is running

-- If the LED is not toggling, verify the keyboard is in input group:

-- sudo usermod -aG input $USER  (handled by core role)

-- =============================================================================
