-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- dotfiles/hyprland/conf.d/input.conf

hl.config({
    input = {
        kb_layout = "us",
        numlock_by_default = true,
        follow_mouse = 1,
        mouse_refocus = true,
        -- -1.0 to 1.0 — 0 = no acceleration ; Setting 0.2, adaptive to mimic MacOS feel
        sensitivity = 0.2,
        accel_profile = "adaptive",
        touchpad = {
            -- 1. Natural Scrolling (macOS style)
            natural_scroll = true,
            scroll_factor = 0.8,
            -- 2. Tap-to-click (Essential for the Mac feel)
            tap_to_click = true,
            -- 3. macOS Style Clicking: 
            -- 1 finger = Left Click, 2 fingers = Right Click, 3 fingers = Middle Click
            -- This disables the "bottom right corner = right click" behavior.
            clickfinger_behavior = true,
            -- 4. Smoothness & Precision
            disable_while_typing = true,
            middle_button_emulation = true,
            -- Optional: Set to 'true' if you want a very light tap to register
            tap_and_drag = true,
            drag_lock = false,
        },
    },
})

-- ── Gestures ──────────────────────────────────────────────────────────────────

-- In Hyprland 0.55, "gesture" is a top-level keyword handler, NOT a subkey

-- inside a gestures {} block. The old workspace_swipe_* subkeys are gone.

-- Syntax: gesture = <fingers>, <direction>, <action>[, <options>]

-- Actions: workspace, special, resize, move, close, float, fullscreen, cursor_zoom

hl.gesture({
    fingers = 3,
    direction = "horizontal",
    action = "workspace",
})

hl.config({
    binds = {
        allow_workspace_cycles = true,
    },
})
