-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- dotfiles/hyprland/conf.d/keybinds.conf

-- =============================================================================

-- Key: SUPER = Windows/Meta key  

-- =============================================================================

local mod = "SUPER"

local term = "kitty"

local menu = "fuzzel"

local browser = "firefox"

local files = "dolphin"

local lock = "hyprlock"

-- ── Session ───────────────────────────────────────────────────────────────────

hl.bind(mod .. " + " .. "SHIFT" .. " + " .. "Q", hl.dsp.window.close())

hl.bind(mod .. " + " .. "SHIFT" .. " + " .. "E", hl.dsp.exit())

hl.bind(mod .. " + " .. "L", hl.dsp.exec_cmd("hyprlock"))

hl.bind(mod .. " + " .. "F1", hl.dsp.exec_cmd("~/.config/hypr/scripts/help.sh"))

-- ── Apps ──────────────────────────────────────────────────────────────────────

hl.bind(mod .. " + " .. "Return", hl.dsp.exec_cmd("kitty"))

hl.bind(mod .. " + " .. "Space", hl.dsp.exec_cmd("fuzzel"))

hl.bind(mod .. " + " .. "B", hl.dsp.exec_cmd("firefox"))

hl.bind(mod .. " + " .. "E", hl.dsp.exec_cmd("dolphin"))

hl.bind(mod .. " + " .. "S", hl.dsp.exec_cmd("~/.config/hypr/scripts/screenshot.sh screen"))

-- full screen → swappy

hl.bind(mod .. " + " .. "SHIFT" .. " + " .. "S", hl.dsp.exec_cmd("~/.config/hypr/scripts/screenshot.sh region"))

-- region → swappy

hl.bind(mod .. " + " .. "SHIFT" .. " + " .. "C", hl.dsp.exec_cmd("cliphist list| fuzzel --dmenu| cliphist decode| wl-copy"))

-- ── Window layout ─────────────────────────────────────────────────────────────

hl.bind(mod .. " + " .. "F", hl.dsp.window.fullscreen())

hl.bind(mod .. " + " .. "SHIFT" .. " + " .. "F", hl.dsp.window.fullscreen())

-- fake-fullscreen

hl.bind(mod .. " + " .. "V", hl.dsp.window.float())

hl.bind(mod .. " + " .. "P", hl.dsp.window.pseudo())

-- dwindle pseudo tile

hl.bind(mod .. " + " .. "G", hl.dsp.group.toggle())

-- ── Split direction (dwindle) — i3-style pre-split ────────────────────────────

-- Set which direction the NEXT window opens relative to current focus

-- Super+Ctrl+H/L = next window opens to the left/right (horizontal split)

-- Super+Ctrl+K/J = next window opens above/below (vertical split)

hl.bind(mod .. " + " .. "CTRL" .. " + " .. "H", hl.dsp.layout("preselect l"))

hl.bind(mod .. " + " .. "CTRL" .. " + " .. "L", hl.dsp.layout("preselect r"))

hl.bind(mod .. " + " .. "CTRL" .. " + " .. "K", hl.dsp.layout("preselect u"))

hl.bind(mod .. " + " .. "CTRL" .. " + " .. "J", hl.dsp.layout("preselect d"))

hl.bind(mod .. " + " .. "CTRL" .. " + " .. "left", hl.dsp.layout("preselect l"))

hl.bind(mod .. " + " .. "CTRL" .. " + " .. "right", hl.dsp.layout("preselect r"))

hl.bind(mod .. " + " .. "CTRL" .. " + " .. "up", hl.dsp.layout("preselect u"))

hl.bind(mod .. " + " .. "CTRL" .. " + " .. "down", hl.dsp.layout("preselect d"))

-- Toggle spawn direction — flip between → horizontal (right) and ↓ vertical (below)

-- i3 equivalent: split h / split v. Persistent per-node via preserve_split.

hl.bind(mod .. " + " .. "T", hl.dsp.exec_cmd("~/.config/hypr/scripts/toggle-split.sh"))

-- Toggle layout: dwindle ↔ master (Super+O — "O" for orientation)

hl.bind(mod .. " + " .. "O", hl.dsp.exec_cmd("hyprctl keyword general:layout master"))

hl.bind(mod .. " + " .. "SHIFT" .. " + " .. "O", hl.dsp.exec_cmd("hyprctl keyword general:layout dwindle"))

-- Master layout helpers (useful when toggled into master mode)

hl.bind(mod .. " + " .. "SHIFT" .. " + " .. "Return", hl.dsp.layout("swapwithmaster"))

hl.bind(mod .. " + " .. "comma", hl.dsp.layout("removemaster"))

hl.bind(mod .. " + " .. "period", hl.dsp.layout("addmaster"))

-- Group management (stack windows in same tile slot)

hl.bind(mod .. " + " .. "ALT" .. " + " .. "H", hl.dsp.window.move({ into_group = "left" }))

hl.bind(mod .. " + " .. "ALT" .. " + " .. "L", hl.dsp.window.move({ into_group = "right" }))

hl.bind(mod .. " + " .. "ALT" .. " + " .. "K", hl.dsp.window.move({ into_group = "up" }))

hl.bind(mod .. " + " .. "ALT" .. " + " .. "J", hl.dsp.window.move({ into_group = "down" }))

hl.bind(mod .. " + " .. "ALT" .. " + " .. "left", hl.dsp.window.move({ into_group = "left" }))

hl.bind(mod .. " + " .. "ALT" .. " + " .. "right", hl.dsp.window.move({ into_group = "right" }))

hl.bind(mod .. " + " .. "ALT" .. " + " .. "escape", hl.dsp.window.move({ out_of_group = true }))

-- ── Focus (Vim-style + arrow keys) ───────────────────────────────────────────

-- smart-focus.sh: tries movefocus, falls back to cyclenext if no neighbor (i3-style)

hl.bind(mod .. " + " .. "H", hl.dsp.exec_cmd("~/.config/hypr/scripts/smart-focus.sh l"))

hl.bind(mod .. " + " .. "L", hl.dsp.exec_cmd("~/.config/hypr/scripts/smart-focus.sh r"))

hl.bind(mod .. " + " .. "K", hl.dsp.exec_cmd("~/.config/hypr/scripts/smart-focus.sh u"))

hl.bind(mod .. " + " .. "J", hl.dsp.exec_cmd("~/.config/hypr/scripts/smart-focus.sh d"))

hl.bind(mod .. " + " .. "left", hl.dsp.exec_cmd("~/.config/hypr/scripts/smart-focus.sh l"))

hl.bind(mod .. " + " .. "right", hl.dsp.exec_cmd("~/.config/hypr/scripts/smart-focus.sh r"))

hl.bind(mod .. " + " .. "up", hl.dsp.exec_cmd("~/.config/hypr/scripts/smart-focus.sh u"))

hl.bind(mod .. " + " .. "down", hl.dsp.exec_cmd("~/.config/hypr/scripts/smart-focus.sh d"))

-- ── Move / swap windows ───────────────────────────────────────────────────────

-- HJKL — swap with adjacent neighbor (needs a window in that direction)

hl.bind(mod .. " + " .. "SHIFT" .. " + " .. "H", hl.dsp.window.swap({ direction = "left" }))

hl.bind(mod .. " + " .. "SHIFT" .. " + " .. "L", hl.dsp.window.swap({ direction = "right" }))

hl.bind(mod .. " + " .. "SHIFT" .. " + " .. "K", hl.dsp.window.swap({ direction = "up" }))

hl.bind(mod .. " + " .. "SHIFT" .. " + " .. "J", hl.dsp.window.swap({ direction = "down" }))

-- Arrows — smart move: tries movewindow, creates vertical split if no neighbor above/below

hl.bind(mod .. " + " .. "SHIFT" .. " + " .. "left", { direction = "l" })

hl.bind(mod .. " + " .. "SHIFT" .. " + " .. "right", { direction = "r" })

hl.bind(mod .. " + " .. "SHIFT" .. " + " .. "up", hl.dsp.exec_cmd("~/.config/hypr/scripts/smart-movewindow.sh u"))

hl.bind(mod .. " + " .. "SHIFT" .. " + " .. "down", hl.dsp.exec_cmd("~/.config/hypr/scripts/smart-movewindow.sh d"))

-- ── Resize (hold $mod + R, then arrow/HJKL) ──────────────────────────────────

hl.bind(mod .. " + " .. "R", hl.dsp.submap("resize"))

hl.define_submap("resize", function()
    -- resizeactive's hyprlang delta form (bind, dx dy) maps to
    -- hl.dsp.window.resize({ x, y, relative = true }); `binde` (repeat while
    -- held) maps to { repeating = true }.
    hl.bind("H",     hl.dsp.window.resize({ x = -30, y = 0, relative = true }),   { repeating = true })
    hl.bind("L",     hl.dsp.window.resize({ x = 30, y = 0, relative = true }),    { repeating = true })
    hl.bind("K",     hl.dsp.window.resize({ x = 0, y = -30, relative = true }),   { repeating = true })
    hl.bind("J",     hl.dsp.window.resize({ x = 0, y = 30, relative = true }),    { repeating = true })
    hl.bind("left",  hl.dsp.window.resize({ x = -30, y = 0, relative = true }),   { repeating = true })
    hl.bind("right", hl.dsp.window.resize({ x = 30, y = 0, relative = true }),    { repeating = true })
    hl.bind("up",    hl.dsp.window.resize({ x = 0, y = -30, relative = true }),   { repeating = true })
    hl.bind("down",  hl.dsp.window.resize({ x = 0, y = 30, relative = true }),    { repeating = true })
    hl.bind("escape", hl.dsp.submap("reset"))
    hl.bind("Return", hl.dsp.submap("reset"))
end)


-- ── Workspaces 1–10 ───────────────────────────────────────────────────────────

hl.bind(mod .. " + " .. 1, hl.dsp.focus({ workspace = 1 }))

hl.bind(mod .. " + " .. 2, hl.dsp.focus({ workspace = 2 }))

hl.bind(mod .. " + " .. 3, hl.dsp.focus({ workspace = 3 }))

hl.bind(mod .. " + " .. 4, hl.dsp.focus({ workspace = 4 }))

hl.bind(mod .. " + " .. 5, hl.dsp.focus({ workspace = 5 }))

hl.bind(mod .. " + " .. 6, hl.dsp.focus({ workspace = 6 }))

hl.bind(mod .. " + " .. 7, hl.dsp.focus({ workspace = 7 }))

hl.bind(mod .. " + " .. 8, hl.dsp.focus({ workspace = 8 }))

hl.bind(mod .. " + " .. 9, hl.dsp.focus({ workspace = 9 }))

hl.bind(mod .. " + " .. 0, hl.dsp.focus({ workspace = 10 }))

hl.bind(mod .. " + " .. "SHIFT" .. " + " .. 1, hl.dsp.window.move({ workspace = 1 }))

hl.bind(mod .. " + " .. "SHIFT" .. " + " .. 2, hl.dsp.window.move({ workspace = 2 }))

hl.bind(mod .. " + " .. "SHIFT" .. " + " .. 3, hl.dsp.window.move({ workspace = 3 }))

hl.bind(mod .. " + " .. "SHIFT" .. " + " .. 4, hl.dsp.window.move({ workspace = 4 }))

hl.bind(mod .. " + " .. "SHIFT" .. " + " .. 5, hl.dsp.window.move({ workspace = 5 }))

hl.bind(mod .. " + " .. "SHIFT" .. " + " .. 6, hl.dsp.window.move({ workspace = 6 }))

hl.bind(mod .. " + " .. "SHIFT" .. " + " .. 7, hl.dsp.window.move({ workspace = 7 }))

hl.bind(mod .. " + " .. "SHIFT" .. " + " .. 8, hl.dsp.window.move({ workspace = 8 }))

hl.bind(mod .. " + " .. "SHIFT" .. " + " .. 9, hl.dsp.window.move({ workspace = 9 }))

hl.bind(mod .. " + " .. "SHIFT" .. " + " .. 0, hl.dsp.window.move({ workspace = 10 }))

-- Cycle workspaces

hl.bind(mod .. " + " .. "Tab", hl.dsp.focus({ workspace = "previous" }))

hl.bind(mod .. " + " .. "mouse_down", hl.dsp.focus({ workspace = "e+1" }))

hl.bind(mod .. " + " .. "mouse_up", hl.dsp.focus({ workspace = "e-1" }))

hl.bind(mod .. " + " .. "bracketright", hl.dsp.focus({ workspace = "e+1" }))

hl.bind(mod .. " + " .. "bracketleft", hl.dsp.focus({ workspace = "e-1" }))

-- ── Scratchpad ────────────────────────────────────────────────────────────────

hl.bind(mod .. " + " .. "grave", hl.dsp.workspace.toggle_special("scratchpad"))

hl.bind(mod .. " + " .. "SHIFT" .. " + " .. "grave", hl.dsp.window.move({ workspace = "special:scratchpad" }))

-- ── Mouse binds ───────────────────────────────────────────────────────────────

hl.bind(mod .. " + " .. "mouse:272", hl.dsp.window.drag(), { mouse = true })

hl.bind(mod .. " + " .. "mouse:273", hl.dsp.window.resize(), { mouse = true })
