-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- dotfiles/hyprland/conf.d/look.conf

-- Visual appearance — gaps, borders, rounding, shadows, blur

--

-- Palette source: ansible/inventory/group_vars/all.yml

--   rabble_color_bg:      #0a0010   Deep void

--   rabble_color_primary: #ff2d78   Hot magenta

--   rabble_color_accent:  #00f5ff   Electric cyan

--   rabble_color_violet:  #bf5fff   Soft violet

--   rabble_color_text:    #e8d5ff   Off-white / purple tint

--   rabble_color_muted:   #8860aa   Muted purple

--   rabble_color_surface: #120025   Elevated surface

hl.config({
    general = {
        gaps_in = 4,
        gaps_out = 10,
        border_size = 2,
        -- Active: magenta → cyan gradient (synthwave sweep)
        layout = "dwindle",
        resize_on_border = true,
        extend_border_grab_area = 10,
        col = {
            active_border = { colors = { "rgba(ff2d78ff)", "rgba(00f5ffff)" }, angle = 45 },
            inactive_border = "rgba(8860aa33)",
        },
    },
})

hl.config({
    decoration = {
        rounding = 10,
        active_opacity = 1.0,
        inactive_opacity = 1.0,
        -- GPU-load reduction (4K AMD iGPU): opaque inactive windows drop per-window translucent compositing cost
        fullscreen_opacity = 1.0,
        shadow = {
            enabled = true,
            range = 24,
            render_power = 3,
            color = "rgba(bf5fff18)",
            -- violet bridges magenta→cyan sweep; static (shadow can't animate)
            color_inactive = "rgba(0a001099)",
            offset = "0 4",
        },
        blur = {
            enabled = true,
            size = 6,
            -- GPU-load reduction (4K AMD iGPU): cost scales with size×passes
            passes = 2,
            -- GPU-load reduction (4K AMD iGPU): cost scales with size×passes
            new_optimizations = true,
            xray = true,
            -- GPU-load reduction (4K AMD iGPU): skip blurring what's behind a window instead of full stacked blur
            noise = 0.02,
            contrast = 0.9,
            brightness = 0.8,
            popups = true,
        },
    },
})

hl.config({
    dwindle = {
        preserve_split = true,
        -- split direction remembered per-node (enables togglesplit persistence)
        smart_split = false,
        -- don't auto-decide h/v; user controls direction via togglesplit
        smart_resizing = true,
        force_split = 2,
        -- new window always goes right/below the focused one
    },
})

hl.config({
    master = {
        new_status = "slave",
        mfact = 0.55,
        orientation = "top",
    },
})

hl.config({
    misc = {
        disable_hyprland_logo = true,
        disable_splash_rendering = true,
        mouse_move_enables_dpms = true,
        key_press_enables_dpms = true,
        vrr = 1,
        focus_on_activate = false,
        animate_manual_resizes = true,
        animate_mouse_windowdragging = true,
    },
})

hl.config({
    group = {
        groupbar = {
            enabled = true,
            height = 3,
            render_titles = false,
            col = {
                active = "rgba(ff2d78ff)",
                inactive = "rgba(8860aa55)",
            },
        },
        col = {
            border_active = "rgba(ff2d78ff)",
            border_inactive = "rgba(8860aa33)",
            border_locked_active = "rgba(00f5ffff)",
            border_locked_inactive = "rgba(12002566)",
        },
    },
})
