-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- conf.d/monitors.conf

-- =============================================================================

-- Monitor layout and hotplug rules.

-- Run `hyprctl monitors` to find exact output names on your system.

-- =============================================================================

-- ── Primary display ───────────────────────────────────────────────────────────

-- No catch-all here — Hyprland auto-configures unlisted displays natively,

-- preserving whatever scale/resolution they negotiate.

-- ── HDMI hotplug ─────────────────────────────────────────────────────────────

-- Activates automatically when HDMI-A-1 is connected.

-- Workspace 11 is pinned to this output (see workspaces.conf).

-- Position: auto-right of the primary display.

-- If your port enumerates as HDMI-A-2 or DP-1, duplicate this line with the

-- correct name — the hdmi-hotplug.sh script matches on "HDMI-*" prefix.

hl.monitor({
    output   = "HDMI-A-1",
    mode     = "1920x1080@59.94",
    position = "auto-right",
    scale    = 1,
})
