-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- conf.d/windowrules.conf

-- =============================================================================

-- Window & Layer Rules — Hyprland 0.55 (legacy hyprlang format)

-- =============================================================================

-- Syntax reference (0.55 legacy .conf):

--   windowrule = <effect> <value>, match:<prop> <regex>[, match:<prop> <regex>, ...]

--   windowrule = <effect> <value>[, <effect> <value>, ...]

--

-- Effects and matchers are comma-separated tokens. Each token is split on the

-- FIRST space: left side = effect name OR "match:<prop>", right = value/regex.

-- Effects: float, tile, center, size, pin, opacity, workspace, idle_inhibit,

--          no_initial_focus, keep_aspect_ratio, immediate, move, monitor, etc.

-- Boolean effects (float, center, pin, keep_aspect_ratio, immediate, ...):

--   value must be "true"/"false"/"1"/"0" — e.g. "float true", "center true"

-- Matchers: match:class, match:title, match:initial_class, match:initial_title,

--           match:modal, match:float, match:xwayland, match:fullscreen, etc.

-- Rule order: all matching rules are applied in file order; LAST rule wins per

--   effect. Put catch-alls FIRST, specific rules LAST to override.

--

-- IMPORTANT: workspace assignments apply to ALL windows matching the class,

-- including child dialogs. Use match:modal false AND match:float false to

-- exclude transient/modal dialogs from workspace assignments.

-- =============================================================================

-- ── Modal / transient dialogs — catch ALL apps first ─────────────────────────

-- Any window that is modal (transient dialog) floats and centers regardless of

-- class. This runs FIRST (lowest priority) so app-specific rules can still

-- override. Modal = true catches Qt/GTK dialogs that set transient_for.

hl.window_rule({
    name  = "float_true_1",
    match = {
        modal = true,
    },
    float = true,
})

hl.window_rule({
    name  = "center_true_1",
    match = {
        modal = true,
    },
    center = true,
})

-- ── Default floating window size ─────────────────────────────────────────────

-- Only applies to windows that are already floating (match:float true prevents

-- this from sizing tiled windows). Specific app rules below override.

-- NOTE: "80% 80%" uses muParser expression syntax — percent of monitor size.

-- This does NOT apply to modal dialogs (they have their own intrinsic size).

hl.window_rule({
    name  = "size_80__80_",
    match = {
        float = true,
        modal = false,
    },
    size = "80% 80%",
})

-- ── Idle inhibit ──────────────────────────────────────────────────────────────

hl.window_rule({
    name  = "idle_inhibit_fullscr_1",
    match = {
        class = "^(mpv|vlc|celluloid)$",
    },
    idle_inhibit = "fullscreen",
})

hl.window_rule({
    name  = "idle_inhibit_fullscr_2",
    match = {
        class = "^(firefox|chromium|brave-browser|zen)$",
    },
    idle_inhibit = "fullscreen",
})

-- ── Picture-in-Picture ────────────────────────────────────────────────────────

hl.window_rule({
    name  = "float_true_2",
    match = {
        title = "^([Pp]icture[-\\s]?[Ii]n[-\\s]?[Pp]icture)",
    },
    float = true,
})

hl.window_rule({
    name  = "keep_aspect_ratio_tr",
    match = {
        title = "^([Pp]icture[-\\s]?[Ii]n[-\\s]?[Pp]icture)",
    },
    keep_aspect_ratio = true,
})

hl.window_rule({
    name  = "pin_true",
    match = {
        title = "^([Pp]icture[-\\s]?[Ii]n[-\\s]?[Pp]icture)",
    },
    pin = true,
})

hl.window_rule({
    name  = "size_25__25_",
    match = {
        title = "^([Pp]icture[-\\s]?[Ii]n[-\\s]?[Pp]icture)",
    },
    size = "25% 25%",
})

hl.window_rule({
    name  = "move_73__72_",
    match = {
        title = "^([Pp]icture[-\\s]?[Ii]n[-\\s]?[Pp]icture)",
    },
    move = "73% 72%",
})

-- ── Float: system dialogs and file pickers ────────────────────────────────────

-- Generic title-based float (save/open dialogs in many apps)

hl.window_rule({
    name  = "float_true_3",
    match = {
        title = "^(Open|Save|Save As|Open File|Open Folder|Select File)",
    },
    float = true,
})

hl.window_rule({
    name  = "float_true_4",
    match = {
        title = "^(Confirm|Warning|Error|Alert|Question|Information)",
    },
    float = true,
})

hl.window_rule({
    name  = "float_true_5",
    match = {
        title = "^(File Manager|File Browser|File Chooser)",
    },
    float = true,
})

hl.window_rule({
    name  = "float_true_6",
    match = {
        title = "(Preference|Preferences|Settings|Properties|About)$",
    },
    float = true,
})

-- Portal file picker

hl.window_rule({
    name  = "float_true_7",
    match = {
        class = "^(xdg-desktop-portal-gtk)$",
    },
    float = true,
})

hl.window_rule({
    name  = "float_true_8",
    match = {
        class = "^(xdg-portal-dialog)$",
    },
    float = true,
})

-- ── termfilechooser portal — yazi in kitty, floating file picker ──────────────

hl.window_rule({
    name  = "float_true_9",
    match = {
        class = "^(kitty)$",
        title = "^(termfilechooser)",
    },
    float = true,
})

hl.window_rule({
    name  = "size_900_580_1",
    match = {
        class = "^(kitty)$",
        title = "^(termfilechooser)",
    },
    size = "900 580",
})

hl.window_rule({
    name  = "center_true_2",
    match = {
        class = "^(kitty)$",
        title = "^(termfilechooser)",
    },
    center = true,
})

-- ── RaBbLE agent popup (LLM usage, etc.) ─────────────────────────────────────

hl.window_rule({
    name  = "float_true_10",
    match = {
        class = "^(rabble-popup)$",
    },
    float = true,
})

hl.window_rule({
    name  = "center_true_3",
    match = {
        class = "^(rabble-popup)$",
    },
    center = true,
})

hl.window_rule({
    name  = "size_680_420",
    match = {
        class = "^(rabble-popup)$",
    },
    size = "680 420",
})

hl.window_rule({
    name  = "opacity_0_94_0_94",
    match = {
        class = "^(rabble-popup)$",
    },
    opacity = "0.94 0.94",
})

-- ── Float: calculator, color picker, calendar popups ─────────────────────────

hl.window_rule({
    name  = "float_true_11",
    match = {
        class = "^(gnome-calculator|kcalc|qalculate-gtk)$",
    },
    float = true,
})

hl.window_rule({
    name  = "float_true_12",
    match = {
        class = "^(Yad|yad)$",
    },
    float = true,
})

hl.window_rule({
    name  = "float_true_13",
    match = {
        class = "^(zenity)$",
    },
    float = true,
})

-- ── Float: network and bluetooth settings ─────────────────────────────────────

hl.window_rule({
    name  = "float_true_14",
    match = {
        class = "^(nm-connection-editor)$",
    },
    float = true,
})

hl.window_rule({
    name  = "float_true_15",
    match = {
        class = "^(nm-applet)$",
    },
    float = true,
})

hl.window_rule({
    name  = "float_true_16",
    match = {
        class = "^(bluedevil-wizard|blueberry)$",
    },
    float = true,
})

hl.window_rule({
    name  = "float_true_17",
    match = {
        class = "^(blueman-manager)$",
    },
    float = true,
})

hl.window_rule({
    name  = "size_700_500",
    match = {
        class = "^(nm-connection-editor)$",
    },
    size = "700 500",
})

hl.window_rule({
    name  = "size_600_450",
    match = {
        class = "^(blueman-manager|blueberry)$",
    },
    size = "600 450",
})

hl.window_rule({
    name  = "center_true_4",
    match = {
        class = "^(nm-connection-editor)$",
    },
    center = true,
})

hl.window_rule({
    name  = "center_true_5",
    match = {
        class = "^(blueman-manager|blueberry)$",
    },
    center = true,
})

-- ── Float: volume / audio control ────────────────────────────────────────────

hl.window_rule({
    name  = "float_true_18",
    match = {
        class = "^(pavucontrol|pavucontrol-qt)$",
    },
    float = true,
})

hl.window_rule({
    name  = "size_800_500",
    match = {
        class = "^(pavucontrol|pavucontrol-qt)$",
    },
    size = "800 500",
})

hl.window_rule({
    name  = "center_true_6",
    match = {
        class = "^(pavucontrol|pavucontrol-qt)$",
    },
    center = true,
})

-- ── UP Studio (TierTime Cetus3D MK2 slicer, via Bottles) ─────────────────────

-- Reverted 2026-07-27 (S205): the float + dedicated-workspace + launch-script

-- positioning combo (see git history for the removed rules and

-- scripts/upstudio3-launch.sh) was fighting these windows more than helping —

-- Bottles' XWayland-under-Wine windows resist windowrule/hyprctl-imposed

-- geometry inconsistently, causing unreliable placement/z-order while

-- debugging the printer-connection issue. Launch plain (`bottles-cli run -b

-- UPStudio3 -p "UP Studio3"`) on an empty workspace instead; let it use

-- Hyprland's default tiling. Revisit a positioning rule only once the app

-- itself is actually working end to end.

-- ── Float: file manager — centered smallish floating window ──────────────────

-- Covers Dolphin (target) and Thunar/Nemo/Nautilus alternatives.

-- Dolphin's Wayland app-ID is org.kde.dolphin — the .*dolphin.* pattern catches

-- both the Wayland app-ID and the X11 StartupWMClass.

-- Child dialogs (rename, copy, properties) have the SAME class and are also

-- matched here — they float, get centered, and we DON'T force a fixed size on

-- them so their intrinsic Qt dialog size is preserved (modal rule handles centering).

hl.window_rule({
    name  = "float_true_19",
    match = {
        class = "^(.*[Dd]olphin.*|.*[Tt]hunar.*|.*[Nn]emo.*|.*[Nn]autilus.*)$",
    },
    float = true,
})

hl.window_rule({
    name  = "center_true_7",
    match = {
        class = "^(.*[Dd]olphin.*|.*[Tt]hunar.*|.*[Nn]emo.*|.*[Nn]autilus.*)$",
    },
    center = true,
})

-- Only size the MAIN file manager window, not its dialogs

-- (modal dialogs have match:modal true so this match:modal false scopes it out)

hl.window_rule({
    name  = "size_900_580_2",
    match = {
        class = "^(.*[Dd]olphin.*|.*[Tt]hunar.*|.*[Nn]emo.*|.*[Nn]autilus.*)$",
        modal = false,
    },
    size = "900 580",
})

-- ── Float: Firefox popups and secondary windows ───────────────────────────────

-- Main Firefox window tiles normally. Popups, dialogs, and child windows float.

-- PiP is excluded here — handled above.

hl.window_rule({
    name  = "float_true_20",
    match = {
        class = "^(firefox|firefox-esr|zen-browser|zen|Zen)$",
        title = "^(Firefox — Sharing Indicator)",
    },
    float = true,
})

hl.window_rule({
    name  = "float_true_21",
    match = {
        class = "^(firefox|firefox-esr|zen-browser|zen|Zen)$",
        title = "^(Opening )",
    },
    float = true,
})

hl.window_rule({
    name  = "float_true_22",
    match = {
        class = "^(firefox|firefox-esr|zen-browser|zen|Zen)$",
        title = "^(Extension:)",
    },
    float = true,
})

hl.window_rule({
    name  = "float_true_23",
    match = {
        class = "^(firefox|firefox-esr|zen-browser|zen|Zen)$",
        title = "^(Firefox)$",
    },
    float = true,
})

hl.window_rule({
    name  = "float_true_24",
    match = {
        class = "^(firefox|firefox-esr|zen-browser|zen|Zen)$",
        title = "^(About )",
    },
    float = true,
})

hl.window_rule({
    name  = "float_true_25",
    match = {
        class = "^(firefox|firefox-esr|zen-browser|zen|Zen)$",
        title = "^(Print)",
    },
    float = true,
})

hl.window_rule({
    name  = "float_true_26",
    match = {
        class = "^(firefox|firefox-esr|zen-browser|zen|Zen)$",
        title = "( — Page Info)$",
    },
    float = true,
})

hl.window_rule({
    name  = "float_true_27",
    match = {
        class = "^(firefox|firefox-esr|zen-browser|zen|Zen)$",
        title = "^(Enter Password)",
    },
    float = true,
})

hl.window_rule({
    name  = "float_true_28",
    match = {
        class = "^(firefox|firefox-esr|zen-browser|zen|Zen)$",
        title = "^(Save )",
    },
    float = true,
})

hl.window_rule({
    name  = "center_true_8",
    match = {
        class = "^(firefox|firefox-esr|zen-browser|zen|Zen)$",
        title = "^(Firefox)$",
    },
    center = true,
})

hl.window_rule({
    name  = "center_true_9",
    match = {
        class = "^(firefox|firefox-esr|zen-browser|zen|Zen)$",
        title = "^(About )",
    },
    center = true,
})

hl.window_rule({
    name  = "center_true_10",
    match = {
        class = "^(firefox|firefox-esr|zen-browser|zen|Zen)$",
        title = "^(Print)",
    },
    center = true,
})

-- ── Float: general application popups ────────────────────────────────────────

-- Catch common popup/dialog title patterns across all apps

hl.window_rule({
    name  = "float_true_29",
    match = {
        title = "^(About )",
    },
    float = true,
})

hl.window_rule({
    name  = "float_true_30",
    match = {
        title = "^(Preferences)$",
    },
    float = true,
})

hl.window_rule({
    name  = "float_true_31",
    match = {
        title = "^(Settings)$",
    },
    float = true,
})

hl.window_rule({
    name  = "float_true_32",
    match = {
        title = "^(Properties)$",
    },
    float = true,
})

hl.window_rule({
    name  = "float_true_33",
    match = {
        title = "( Properties)$",
    },
    float = true,
})

hl.window_rule({
    name  = "float_true_34",
    match = {
        title = "^(Choose )",
    },
    float = true,
})

hl.window_rule({
    name  = "float_true_35",
    match = {
        title = "^(Select )",
    },
    float = true,
})

hl.window_rule({
    name  = "float_true_36",
    match = {
        title = "^(Pick )",
    },
    float = true,
})

hl.window_rule({
    name  = "center_true_11",
    match = {
        title = "^(About )",
    },
    center = true,
})

hl.window_rule({
    name  = "center_true_12",
    match = {
        title = "^(Preferences)$",
    },
    center = true,
})

hl.window_rule({
    name  = "center_true_13",
    match = {
        title = "^(Settings)$",
    },
    center = true,
})

-- ── File picker sizing ────────────────────────────────────────────────────────

hl.window_rule({
    name  = "size_900_600",
    match = {
        class = "^(xdg-desktop-portal-gtk)$",
    },
    size = "900 600",
})

hl.window_rule({
    name  = "center_true_14",
    match = {
        class = "^(xdg-desktop-portal-gtk)$",
    },
    center = true,
})

-- ── IDE: suppress spurious popup focus ───────────────────────────────────────

hl.window_rule({
    name  = "no_initial_focus_tru_1",
    match = {
        class = "^(.*jetbrains.*)$",
        title = "^(win[0-9]+)$",
    },
    no_initial_focus = true,
})

hl.window_rule({
    name  = "no_initial_focus_tru_2",
    match = {
        class = "^(VSCodium|codium)$",
        title = "^(Open File)",
    },
    no_initial_focus = true,
})

hl.window_rule({
    name  = "no_initial_focus_tru_3",
    match = {
        class = "^(Zed)$",
        title = "^(Open File)",
    },
    no_initial_focus = true,
})

-- ── Workspace assignments ─────────────────────────────────────────────────────

-- IMPORTANT: Add match:modal false AND match:float false to exclude child dialogs

-- from workspace assignments. Without these, a Firefox "save file" dialog would

-- be sent silently to workspace 2 even when you're on workspace 1.

--

-- ws 1 — terminals (kitty opens here by default via keybind)

-- ws 2 — browser

hl.window_rule({
    name  = "workspace_2_silent_1",
    match = {
        class = "^(firefox|firefox-esr)$",
        modal = false,
        float = false,
    },
    workspace = "2 silent",
})

hl.window_rule({
    name  = "workspace_2_silent_2",
    match = {
        class = "^(zen-browser|zen|Zen)$",
        modal = false,
        float = false,
    },
    workspace = "2 silent",
})

hl.window_rule({
    name  = "workspace_2_silent_3",
    match = {
        class = "^(chromium|brave-browser)$",
        modal = false,
        float = false,
    },
    workspace = "2 silent",
})

-- ws 3 — files

-- workspace assignment removed: file manager floats on current workspace via rules above

-- ws 4 — comms

hl.window_rule({
    name  = "workspace_4_silent_1",
    match = {
        class = "^(Signal|signal)$",
        modal = false,
        float = false,
    },
    workspace = "4 silent",
})

hl.window_rule({
    name  = "workspace_4_silent_2",
    match = {
        class = "^(discord|Discord|vesktop)$",
        modal = false,
        float = false,
    },
    workspace = "4 silent",
})

hl.window_rule({
    name  = "workspace_4_silent_3",
    match = {
        class = "^(slack|Slack)$",
        modal = false,
        float = false,
    },
    workspace = "4 silent",
})

-- ws 9 — monitoring / scratchpad terminals (routed there manually)

-- ws 10 — music / media players

hl.window_rule({
    name  = "workspace_10_silent_1",
    match = {
        class = "^(Spotify|spotify)$",
        modal = false,
        float = false,
    },
    workspace = "10 silent",
})

hl.window_rule({
    name  = "workspace_10_silent_2",
    match = {
        class = "^(mpv|vlc|celluloid)$",
        modal = false,
        float = false,
    },
    workspace = "10 silent",
})

-- ── VM workspace (5) ─────────────────────────────────────────────────────────

-- virt-manager and its VM console windows go to ws 5 automatically.

-- NOT silent — Hyprland follows the window to ws 5 on open so you know it landed.

-- Exclude modals so virt-manager dialogs (new VM wizard, etc.) stay on current ws.

hl.window_rule({
    name  = "workspace_5",
    match = {
        class = "^(virt-manager)$",
        modal = false,
        float = false,
    },
    workspace = 5,
})

-- ── Audio mixer popup (Waybar audio click → scripts/audio-popup.sh) ───────────

-- Toggled from the bar; float + size so it reads as a popup panel, not a full

-- tile. The top-right *position* is set imperatively by audio-popup.sh (Hyprland

-- auto-centers this GTK float and ignores a `move` windowrule for it). Covers the

-- Wayland app_id and the XWayland class. ~480px wide.

hl.window_rule({
    name  = "float_true_37",
    match = {
        class = "^(org\\.pulseaudio\\.pavucontrol|[Pp]avucontrol)$",
    },
    float = true,
})

hl.window_rule({
    name  = "size_480_600",
    match = {
        class = "^(org\\.pulseaudio\\.pavucontrol|[Pp]avucontrol)$",
    },
    size = "480 600",
})

hl.window_rule({
    name  = "opacity_0_96_0_92",
    match = {
        class = "^(org\\.pulseaudio\\.pavucontrol|[Pp]avucontrol)$",
    },
    opacity = "0.96 0.92",
})

-- ── Opacity ───────────────────────────────────────────────────────────────────

-- Terminal — slight transparency to let blur/wallpaper breathe

hl.window_rule({
    name  = "opacity_0_95_0_90",
    match = {
        class = "^(kitty)$",
    },
    opacity = "0.95 0.90",
})

-- File manager — very slight opacity so it doesn't feel painted on

hl.window_rule({
    name  = "opacity_0_97_0_95",
    match = {
        class = "^(dolphin|Dolphin|thunar|Thunar|nemo|Nemo|nautilus|Nautilus)$",
    },
    opacity = "0.97 0.95",
})

-- Code editors — slight transparency; blur+wallpaper bleed through like tinted glass

hl.window_rule({
    name  = "opacity_0_94_0_88",
    match = {
        class = "^(VSCodium|codium|Zed|zed)$",
    },
    opacity = "0.94 0.88",
})

-- Browser — fully opaque

hl.window_rule({
    name  = "opacity_1_0_1_0",
    match = {
        class = "^(firefox|zen-browser|chromium)$",
    },
    opacity = "1.0 1.0",
})

-- ── Tearing / VRR per app ─────────────────────────────────────────────────────

-- Allow tearing for games/video on fullscreen to reduce latency

hl.window_rule({
    name  = "immediate_true_1",
    match = {
        class = "^(steam_app_.*)$",
    },
    immediate = true,
})

hl.window_rule({
    name  = "immediate_true_2",
    match = {
        class = "^(mpv)$",
    },
    immediate = true,
})

-- ── Layer rules ───────────────────────────────────────────────────────────────

-- Valid layerrule effects: blur, blur_popups, ignore_alpha, no_anim, dim_around,

--   xray, animation, order, above_lock, no_screen_share

-- Valid matchers: match:namespace, match:class, match:title, match:modal, etc.

-- ignore_alpha expects a float 0.0–1.0 (alpha threshold for blur to ignore)

hl.layer_rule({
    match = {
        namespace = "match:namespace fuzzel",
    },
    blur = true,
})

hl.layer_rule({
    match = {
        namespace = "match:namespace notifications",
    },
    blur = true,
})

hl.layer_rule({
    match = {
        namespace = "match:namespace notifications",
    },
    ignore_alpha = 0.0,
})

hl.layer_rule({
    match = {
        namespace = "match:namespace swaync-notification-window",
    },
    blur = true,
})

hl.layer_rule({
    match = {
        namespace = "match:namespace swaync-notification-window",
    },
    ignore_alpha = 0.0,
})

hl.layer_rule({
    match = {
        namespace = "match:namespace swaync-control-center",
    },
    blur = true,
})

hl.layer_rule({
    match = {
        namespace = "match:namespace swaync-control-center",
    },
    ignore_alpha = 0.0,
})

hl.layer_rule({
    match = {
        namespace = "match:namespace logout_dialog",
    },
    blur = true,
})
