-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- conf.d/workspaces.conf

-- =============================================================================

-- Workspaces — numbered 1–10, no semantic names

-- Persistent workspaces stay alive when empty.

-- App-to-workspace assignments live in windowrules.conf.

-- =============================================================================

-- Syntax (0.55 legacy .conf):

--   workspace = <id>, <key>:<value>[, <key>:<value>, ...]

-- Keys: persistent:0|1, monitor:NAME, default:0|1, defaultName:NAME,

--       on-created-empty:<cmd>, gapsin:<n>, gapsout:<n>, bordersize:<n>,

--       border:0|1, shadow:0|1, rounding:0|1, decorate:0|1, layout:NAME

-- NOTE: "workspacerule" is NOT a valid keyword — use "workspace" only.

-- =============================================================================

-- ── On-demand (1–10) ──────────────────────────────────────────────────────────

-- No persistent workspaces — each exists only while it has windows. (Persistent

-- workspaces show in the bar even when empty, which is unwanted for now.)

hl.workspace_rule({
    workspace = 1,
    persistent = 0,
})

hl.workspace_rule({
    workspace = 2,
    persistent = 0,
})

hl.workspace_rule({
    workspace = 3,
    persistent = 0,
})

hl.workspace_rule({
    workspace = 4,
    persistent = 0,
})

hl.workspace_rule({
    workspace = 5,
    persistent = 0,
})

hl.workspace_rule({
    workspace = 6,
    persistent = 0,
})

hl.workspace_rule({
    workspace = 7,
    persistent = 0,
})

hl.workspace_rule({
    workspace = 8,
    persistent = 0,
})

hl.workspace_rule({
    workspace = 9,
    persistent = 0,
})

hl.workspace_rule({
    workspace = 10,
    persistent = 0,
})

-- ── HDMI display (workspace 11) ───────────────────────────────────────────────

-- Pinned to HDMI-A-1; migrates back to primary if the monitor is disconnected.

-- The hdmi-hotplug.sh script moves it to the correct output on hotplug.

hl.workspace_rule({
    workspace = 11,
    monitor = "HDMI-A-1",
    persistent = 0,
    defaultName = "hdmi",
})

-- ── Special (scratchpad) ──────────────────────────────────────────────────────

-- on-created-empty: (with hyphen) runs a command when the workspace first opens empty.

hl.workspace_rule({
    workspace = "special:scratchpad",
    ["on-created-empty"] = "kitty",
})
